get_property(ASR_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if(ASR_MULTI_CONFIG)
  set(ASR_RUNTIME_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/$<CONFIG>")
else()
  set(ASR_RUNTIME_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}")
endif()
if(ENABLE_WHISPER)
  set(WHISPER_DIR "${THIRD_PARTY}/whisper.cpp" CACHE PATH "Pinned whisper.cpp source root")
  if(NOT EXISTS "${WHISPER_DIR}/CMakeLists.txt")
    message(FATAL_ERROR "Whisper source missing: run tools/setup_whisper.ps1 first")
  endif()
  set(ASR_RUNTIME "cpu" CACHE STRING "Whisper backend: cpu or cuda")
  set_property(CACHE ASR_RUNTIME PROPERTY STRINGS cpu cuda)
  set(ASR_CUDA_DIR "${THIRD_PARTY}/whisper-cuda" CACHE PATH "Pinned Whisper CUDA runtime")
  if(ASR_RUNTIME STREQUAL "cpu")
    enable_language(C)
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build vendored Whisper statically" FORCE)
    set(WHISPER_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(WHISPER_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(WHISPER_BUILD_SERVER OFF CACHE BOOL "" FORCE)
    set(WHISPER_BUILD_IS_DEV OFF CACHE BOOL "" FORCE)
    set(GGML_NATIVE OFF CACHE BOOL "Portable x64 build" FORCE)
    set(GGML_OPENMP OFF CACHE BOOL "Avoid external OpenMP runtime" FORCE)
    set(GGML_BACKEND_DL OFF CACHE BOOL "Static CPU backend" FORCE)
    set(GGML_CUDA OFF CACHE BOOL "Static CPU distribution" FORCE)
    set(GGML_VULKAN OFF CACHE BOOL "Static CPU distribution" FORCE)
    add_subdirectory("${WHISPER_DIR}" "vendor-whisper" EXCLUDE_FROM_ALL)
  elseif(NOT ASR_RUNTIME STREQUAL "cuda")
    message(FATAL_ERROR "ASR_RUNTIME must be cpu or cuda")
  endif()
  add_library(asr_sdk SHARED src/asr_c_api.cpp src/audio.cpp)
  target_compile_definitions(asr_sdk PRIVATE ASR_BUILD_DLL NOMINMAX ASR_WHISPER_VERSION="1.9.5")
  target_link_libraries(asr_sdk PRIVATE mfplat mfreadwrite mfuuid ole32)
  if(ASR_RUNTIME STREQUAL "cpu")
    target_link_libraries(asr_sdk PRIVATE whisper)
  else()
    # This exact header was compared with the official b5454 release source.
    file(SHA256 "${WHISPER_DIR}/include/whisper.h" ASR_WHISPER_HEADER_SHA)
    if(NOT ASR_WHISPER_HEADER_SHA STREQUAL "a7d19f7feb5be52426628ff07e0602de28a30dc4312d0d0603e1e536753f76dd")
      message(FATAL_ERROR "Whisper header does not match the pinned CUDA runtime ABI")
    endif()
    foreach(dll whisper ggml ggml-base ggml-cuda cublas64_12 cublasLt64_12 cudart64_12)
      if(NOT EXISTS "${ASR_CUDA_DIR}/${dll}.dll")
        message(FATAL_ERROR "Whisper CUDA DLL missing: ${dll}; run tools/setup_whisper_gpu.ps1")
      endif()
    endforeach()
    target_include_directories(asr_sdk PRIVATE "${WHISPER_DIR}/include" "${WHISPER_DIR}/ggml/include")
    target_compile_definitions(asr_sdk PRIVATE ASR_CUDA_RUNTIME)
    file(GLOB ASR_CUDA_DLLS CONFIGURE_DEPENDS "${ASR_CUDA_DIR}/*.dll")
    add_custom_target(asr_runtime ALL
      COMMAND ${CMAKE_COMMAND} -E make_directory "${ASR_RUNTIME_OUTPUT_DIR}"
      COMMAND ${CMAKE_COMMAND} -E copy_if_different ${ASR_CUDA_DLLS} "${ASR_RUNTIME_OUTPUT_DIR}")
    add_dependencies(asr_sdk asr_runtime)
  endif()
  set_target_properties(asr_sdk PROPERTIES OUTPUT_NAME asr PREFIX "")
  add_executable(asr_cli src/asr_main.cpp)
  add_executable(asr_example sdk/examples/asr_example.cpp)
  foreach(target asr_sdk asr_cli asr_example)
    target_compile_definitions(${target} PRIVATE NOMINMAX)
    if(MSVC)
      target_compile_options(${target} PRIVATE /O2 /utf-8)
    elseif(MINGW)
      target_compile_options(${target} PRIVATE -O2)
      target_link_options(${target} PRIVATE -static -static-libgcc -static-libstdc++)
      if(NOT target STREQUAL "asr_sdk")
        target_link_options(${target} PRIVATE -municode)
      endif()
    endif()
  endforeach()
  add_dependencies(asr_cli asr_sdk)
  add_dependencies(asr_example asr_sdk)
endif()

if(ASR_ONLY AND BUILD_TESTING)
  find_package(Python3 COMPONENTS Interpreter QUIET)
  if(Python3_Interpreter_FOUND)
    add_test(NAME asr_integration
      COMMAND ${Python3_EXECUTABLE} ${CMAKE_SOURCE_DIR}/tests/asr_integration.py
              --bin-dir $<TARGET_FILE_DIR:asr_cli>)
    set_tests_properties(asr_integration PROPERTIES WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}" TIMEOUT 300)
  endif()
endif()

if(ENABLE_WHISPER AND BUILD_TESTING)
  add_executable(asr_utf8_test tests/asr_utf8_test.cpp)
  target_include_directories(asr_utf8_test PRIVATE "${CMAKE_SOURCE_DIR}/src")
  # Keep assertions enabled in Release so these regression checks run.
  if(MSVC)
    target_compile_options(asr_utf8_test PRIVATE /UNDEBUG)
  else()
    target_compile_options(asr_utf8_test PRIVATE -UNDEBUG)
  endif()
  add_test(NAME asr_utf8 COMMAND asr_utf8_test)
endif()
